# Generated by Django 5.2.4 on 2025-09-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tauser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tauser',
            options={'ordering': ['nombre'], 'verbose_name': 'Tauser', 'verbose_name_plural': 'Tausers'},
        ),
        migrations.RemoveField(
            model_name='tauser',
            name='codigo',
        ),
    ]
