# Generated by Django 5.2.4 on 2025-08-25 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('billetera', 'Billetera'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20)),
                ('activo', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre_titular', models.CharField(blank=True, max_length=100, null=True)),
                ('ultimos_digitos', models.IntegerField(blank=True, max_length=4, null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('alias_bancario', models.CharField(blank=True, max_length=50, null=True)),
                ('cbu', models.CharField(blank=True, max_length=30, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medio_pagos', to='clientes.cliente')),
            ],
        ),
    ]
