# Generated by Django 5.2.4 on 2025-08-25 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediopago',
            name='cliente',
        ),
        migrations.AddField(
            model_name='mediopago',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='medio_pagos', to=settings.AUTH_USER_MODEL),
        ),
    ]
