# Generated by Django 5.2.4 on 2025-09-04 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_stripe_customer_id'),
        ('pagos', '0002_remove_mediopago_cliente_mediopago_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediopago',
            name='fecha_expiracion',
        ),
        migrations.RemoveField(
            model_name='mediopago',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='mediopago',
            name='ultimos_digitos',
        ),
        migrations.RemoveField(
            model_name='mediopago',
            name='usuario',
        ),
        migrations.AddField(
            model_name='mediopago',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='medio_pagos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='mediopago',
            name='stripe_payment_method_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='tipo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('billetera', 'Billetera'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque')], default='efectivo', max_length=20),
        ),
    ]
