# Generated by Django 5.2.4 on 2025-09-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_remove_mediopago_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediopago',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mediopago',
            name='ultimos_digitos',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
