# Generated by Django 5.2.4 on 2025-09-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_mediopago_usuario_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediopago',
            name='tipo',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta')], default='efectivo', max_length=20),
        ),
    ]
