version: '3.9'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: global_exchange
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    command: gunicorn -c gunicorn.conf.py global_exchange.wsgi
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  pgdata:
  