# Generated by Django 5.2.4 on 2025-08-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'cuentas_permiso',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('FAILED_LOGIN', 'Intento de Login Fallido'), ('ACCOUNT_LOCKED', 'Cuenta Bloqueada'), ('PASSWORD_CHANGE', 'Cambio de Contraseña'), ('EMAIL_VERIFICATION', 'Verificación de Email'), ('PROFILE_UPDATE', 'Actualización de Perfil'), ('TRANSACTION_CREATE', 'Transacción Creada'), ('TRANSACTION_UPDATE', 'Transacción Actualizada'), ('RATE_UPDATE', 'Actualización de Tasa'), ('CLIENT_CHANGE', 'Cambio de Cliente'), ('2FA_SETUP', 'Configuración 2FA'), ('2FA_DISABLE', 'Desactivación 2FA'), ('2FA_VERIFY', 'Verificación 2FA'), ('BACKUP_TOKEN_USED', 'Token de Respaldo Usado'), ('ROLE_ASSIGNED', 'Rol Asignado'), ('ROLE_REMOVED', 'Rol Removido'), ('ROLE_CREATED', 'Rol Creado'), ('ROLE_UPDATED', 'Rol Actualizado'), ('ROLE_DELETED', 'Rol Eliminado')], max_length=50),
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('es_sistema', models.BooleanField(default=False, help_text='Rol del sistema que no se puede eliminar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('permisos', models.ManyToManyField(blank=True, related_name='roles', to='cuentas.permiso')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'cuentas_rol',
                'ordering': ['nombre_rol'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='cuentas.rol'),
        ),
    ]
