# Generated by Django 5.2.4 on 2025-09-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor', models.TextField()),
                ('tipo_valor', models.CharField(choices=[('TEXT', 'Texto'), ('NUMBER', 'Número'), ('BOOLEAN', 'Booleano'), ('EMAIL', 'Email'), ('URL', 'URL')], default='TEXT', max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('categoria', models.CharField(default='General', max_length=50)),
                ('es_editable', models.BooleanField(default=True, help_text='Si la configuración puede ser editada por el usuario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'db_table': 'cuentas_configuracion',
                'ordering': ['categoria', 'clave'],
            },
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('FAILED_LOGIN', 'Intento de Login Fallido'), ('ACCOUNT_LOCKED', 'Cuenta Bloqueada'), ('PASSWORD_CHANGE', 'Cambio de Contraseña'), ('EMAIL_VERIFICATION', 'Verificación de Email'), ('PROFILE_UPDATE', 'Actualización de Perfil'), ('TRANSACTION_CREATE', 'Transacción Creada'), ('TRANSACTION_UPDATE', 'Transacción Actualizada'), ('RATE_UPDATE', 'Actualización de Tasa'), ('CLIENT_CHANGE', 'Cambio de Cliente'), ('2FA_SETUP', 'Configuración 2FA'), ('2FA_DISABLE', 'Desactivación 2FA'), ('2FA_VERIFY', 'Verificación 2FA'), ('BACKUP_TOKEN_USED', 'Token de Respaldo Usado'), ('ROLE_ASSIGNED', 'Rol Asignado'), ('ROLE_REMOVED', 'Rol Removido'), ('ROLE_CREATED', 'Rol Creado'), ('ROLE_UPDATED', 'Rol Actualizado'), ('ROLE_DELETED', 'Rol Eliminado'), ('MEDIO_PAGO_CREATE', 'Medio de pago Asociado'), ('MEDIO_PAGO_DELETED', 'Medio de pago desvinculado')], max_length=50),
        ),
    ]
