# Generated by Django 5.2.4 on 2025-08-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_permiso_alter_registroauditoria_accion_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nro_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
