# Generated by Django 5.2.4 on 2025-09-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_configuracion_alter_registroauditoria_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='tipo_valor',
            field=models.CharField(choices=[('TEXT', 'Texto'), ('NUMBER', 'Número'), ('BOOLEAN', 'Booleano'), ('EMAIL', 'Email'), ('URL', 'URL'), ('MONTO', 'Monto')], default='TEXT', max_length=10),
        ),
    ]
