# Generated by Django 5.2.4 on 2025-09-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_configuracion_tipo_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre legible para la configuración', max_length=100),
        ),
    ]
