# Generated by Django 5.2.4 on 2025-08-26 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('divisas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_reporte', models.CharField(choices=[('HISTORIAL_TRANSACCIONES', 'Historial de Transacciones'), ('TASAS_CAMBIO', 'Tasas de Cambio')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('formato_defecto', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel')], max_length=10)),
                ('filtros_defecto', models.JSONField(default=dict)),
                ('plantilla_consulta', models.TextField(blank=True, help_text='Plantilla de consulta SQL')),
                ('es_publica', models.BooleanField(default=False, help_text='Si la plantilla está disponible para todos los usuarios')),
                ('roles_permitidos', models.JSONField(default=list, help_text='Roles que pueden usar esta plantilla')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_reporte_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reporte',
                'db_table': 'reportes_plantilla',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reporte', models.CharField(max_length=200)),
                ('tipo_reporte', models.CharField(choices=[('HISTORIAL_TRANSACCIONES', 'Historial de Transacciones'), ('TASAS_CAMBIO', 'Tasas de Cambio')], max_length=30)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GENERANDO', 'Generando'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('fecha_desde', models.DateTimeField()),
                ('fecha_hasta', models.DateTimeField()),
                ('filtros', models.JSONField(default=dict, help_text='Filtros aplicados al reporte')),
                ('ruta_archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('tamano_archivo', models.PositiveIntegerField(default=0, help_text='Tamaño del archivo en bytes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha de expiración del archivo', null=True)),
                ('conteo_descargas', models.PositiveIntegerField(default=0)),
                ('max_descargas', models.PositiveIntegerField(default=10, help_text='Número máximo de descargas permitidas')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente específico para el reporte (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='clientes.cliente')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reportes_reporte',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ReporteProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('frecuencia', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual')], max_length=20)),
                ('esta_activo', models.BooleanField(default=True)),
                ('asunto_email', models.CharField(blank=True, max_length=200)),
                ('cuerpo_email', models.TextField(blank=True)),
                ('proxima_ejecucion', models.DateTimeField()),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('conteo_ejecuciones', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_programados_creados', to=settings.AUTH_USER_MODEL)),
                ('destinatarios', models.ManyToManyField(help_text='Usuarios que recibirán el reporte', related_name='reportes_programados', to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_programados', to='reportes.plantillareporte')),
            ],
            options={
                'verbose_name': 'Reporte Programado',
                'verbose_name_plural': 'Reportes Programados',
                'db_table': 'reportes_reporte_programado',
                'ordering': ['proxima_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='MetricaPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_metrica', models.CharField(choices=[('TOTAL_TRANSACCIONES', 'Total de Transacciones'), ('VOLUMEN_DIARIO', 'Volumen Diario'), ('VOLUMEN_MENSUAL', 'Volumen Mensual'), ('MARGEN_GANANCIA', 'Margen de Ganancia'), ('CLIENTES_ACTIVOS', 'Clientes Activos'), ('DISTRIBUCION_MONEDA', 'Distribución por Moneda'), ('TRANSACCION_PROMEDIO', 'Transacción Promedio'), ('TASA_CONVERSION', 'Tasa de Conversión')], max_length=30)),
                ('nombre_metrica', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=8, help_text='Valor principal de la métrica', max_digits=20)),
                ('inicio_periodo', models.DateTimeField()),
                ('fin_periodo', models.DateTimeField()),
                ('metadata', models.JSONField(default=dict, help_text='Datos adicionales de la métrica')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('moneda', models.ForeignKey(blank=True, help_text='Moneda asociada a la métrica', null=True, on_delete=django.db.models.deletion.CASCADE, to='divisas.moneda')),
            ],
            options={
                'verbose_name': 'Métrica del Panel',
                'verbose_name_plural': 'Métricas del Panel',
                'db_table': 'reportes_metrica_panel',
                'ordering': ['-fecha_calculo'],
                'unique_together': {('tipo_metrica', 'inicio_periodo', 'fin_periodo', 'moneda')},
            },
        ),
    ]
