# Generated by Django 5.2.4 on 2025-08-05 23:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('divisas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacionTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transaccion', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=10)),
                ('monto_origen', models.DecimalField(decimal_places=8, max_digits=20)),
                ('monto_destino', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tasa_cambio', models.DecimalField(decimal_places=8, max_digits=20)),
                ('clave_sesion', models.CharField(blank=True, max_length=40)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones', to='clientes.cliente')),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones_como_destino', to='divisas.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones_como_origen', to='divisas.moneda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulación',
                'verbose_name_plural': 'Simulaciones',
                'db_table': 'transacciones_simulacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaccion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_transaccion', models.CharField(blank=True, max_length=20, unique=True)),
                ('tipo_transaccion', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada'), ('ANULADA', 'Anulada'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=20)),
                ('monto_origen', models.DecimalField(decimal_places=8, help_text='Cantidad en moneda origen', max_digits=20)),
                ('monto_destino', models.DecimalField(decimal_places=8, help_text='Cantidad en moneda destino', max_digits=20)),
                ('tasa_cambio', models.DecimalField(decimal_places=8, help_text='Tasa de cambio aplicada', max_digits=20)),
                ('fuente_tasa', models.CharField(default='MANUAL', help_text='Fuente de la tasa de cambio', max_length=50)),
                ('monto_comision', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('referencia_pago', models.CharField(blank=True, help_text='Referencia del pago (número de transferencia, etc.)', max_length=200)),
                ('info_cuenta_bancaria', models.JSONField(blank=True, help_text='Información de cuenta bancaria o billetera', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='clientes.cliente')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='divisas.metodopago')),
                ('moneda_comision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_comision', to='divisas.moneda')),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_como_destino', to='divisas.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_como_origen', to='divisas.moneda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transacciones_transaccion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('tipo_factura', models.CharField(choices=[('TRANSACCION', 'Factura de Transacción'), ('COMISION', 'Factura de Comisión'), ('SERVICIO', 'Factura de Servicio')], max_length=20)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='EMITIDA', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lineas_detalle', models.JSONField(default=list, help_text='Líneas de la factura en formato JSON')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('firma_electronica', models.TextField(blank=True)),
                ('codigo_autoridad_fiscal', models.CharField(blank=True, max_length=100)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='facturas/pdf/')),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='facturas/xml/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clientes.cliente')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='divisas.moneda')),
                ('transaccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='transacciones.transaccion')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'transacciones_factura',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ComisionTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comision', models.CharField(choices=[('CAMBIO', 'Comisión de Cambio'), ('PROCESAMIENTO', 'Comisión de Procesamiento'), ('TRANSFERENCIA', 'Comisión de Transferencia'), ('SERVICIO', 'Comisión de Servicio')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='divisas.moneda')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='transacciones.transaccion')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'db_table': 'transacciones_comision',
            },
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['cliente', 'fecha_creacion'], name='transaccion_cliente_4f36ef_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='transaccion_estado_29b768_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['tipo_transaccion', 'fecha_creacion'], name='transaccion_tipo_tr_53f3c6_idx'),
        ),
    ]
