# Generated by Django 5.2.4 on 2025-09-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que la transacción expirará automáticamente', null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tiempo_expiracion_minutos',
            field=models.PositiveIntegerField(default=30, help_text='Tiempo de expiración en minutos configurado para esta transacción'),
        ),
    ]
