# Generated by Django 5.2.4 on 2025-09-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0007_metodocobro'),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='metodo_cobro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='divisas.metodocobro'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='referencia_cobro',
            field=models.CharField(blank=True, help_text='Referencia del cobro (número de transferencia, etc.)', max_length=200),
        ),
    ]
