# Generated by Django 5.2.4 on 2025-09-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_transaccion_metodo_cobro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='dato_cobro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='dato_pago',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
