# Generated by Django 5.2.4 on 2025-09-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_transaccion_fecha_expiracion_and_more'),
        ('transacciones', '0003_transaccion_dato_cobro_transaccion_dato_pago'),
    ]

    operations = [
    ]
