# Generated by Django 5.2.4 on 2025-08-05 23:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('RETAIL', 'Minorista'), ('CORPORATE', 'Corporativo'), ('VIP', 'VIP')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('limite_transaccion_diario', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Límite diario de transacciones', max_digits=15)),
                ('limite_transaccion_mensual', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), help_text='Límite mensual de transacciones', max_digits=15)),
                ('margen_tasa_preferencial', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), help_text='Margen preferencial de tasa de cambio (porcentaje)', max_digits=5)),
                ('nivel_prioridad', models.PositiveIntegerField(default=1, help_text='Nivel de prioridad (1=más alta, 5=más baja)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Cliente',
                'verbose_name_plural': 'Categorías de Cliente',
                'db_table': 'clientes_categoria',
                'ordering': ['nivel_prioridad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClienteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('PROPIETARIO', 'Propietario'), ('AUTORIZADO', 'Autorizado'), ('CONSULTA', 'Solo Consulta')], default='AUTORIZADO', max_length=20)),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('permisos', models.JSONField(default=dict, help_text='Permisos específicos para este usuario en este cliente')),
            ],
            options={
                'verbose_name': 'Usuario-Cliente',
                'verbose_name_plural': 'Usuarios-Clientes',
                'db_table': 'clientes_cliente_usuario',
            },
        ),
        migrations.CreateModel(
            name='MonedaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Moneda Favorita',
                'verbose_name_plural': 'Monedas Favoritas',
                'db_table': 'clientes_moneda_favorita',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SaldoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saldo de Cliente',
                'verbose_name_plural': 'Saldos de Clientes',
                'db_table': 'clientes_saldo',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('FISICA', 'Persona Física'), ('JURIDICA', 'Persona Jurídica')], max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('PENDIENTE', 'Pendiente')], default='ACTIVO', max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('nombre_empresa', models.CharField(blank=True, max_length=200)),
                ('representante_legal', models.CharField(blank=True, max_length=200)),
                ('numero_identificacion', models.CharField(help_text='DNI/CUIT/RUC u otro documento de identificación', max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('saldo_cuenta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='clientes.categoriacliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes_cliente',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
