# Generated by Django 5.2.4 on 2025-08-26 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('divisas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clienteusuario',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_cliente_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clienteusuario',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='clienteusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='clientes', through='clientes.ClienteUsuario', through_fields=('cliente', 'usuario'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monedafavorita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monedas_favoritas', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='monedafavorita',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorita_por_clientes', to='divisas.moneda'),
        ),
        migrations.AddField(
            model_name='preferenciacliente',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='saldocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_moneda', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='saldocliente',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_cliente', to='divisas.moneda'),
        ),
        migrations.AlterUniqueTogether(
            name='clienteusuario',
            unique_together={('cliente', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='monedafavorita',
            unique_together={('cliente', 'moneda')},
        ),
        migrations.AlterUniqueTogether(
            name='saldocliente',
            unique_together={('cliente', 'moneda')},
        ),
    ]
