# Generated by Django 5.2.4 on 2025-08-21 01:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_compra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Límite máximo de compra', max_digits=15)),
                ('limite_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Límite máximo de venta', max_digits=15)),
                ('frecuencia_maxima', models.PositiveIntegerField(default=0, help_text='Frecuencia máxima de transacciones por día (0 = sin límite)')),
                ('preferencia_tipo_cambio', models.CharField(blank=True, help_text="Preferencia de tipo de cambio (ej: 'preferencial', 'mercado', etc.)", max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Preferencia de Cliente',
                'verbose_name_plural': 'Preferencias de Cliente',
                'db_table': 'clientes_preferencia_cliente',
            },
        ),
    ]
