# Generated by Django 5.2.4 on 2025-09-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='stripe_customer_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
