# Generated by Django 5.2.4 on 2025-09-25 02:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_stripe_customer_id'),
        ('divisas', '0007_metodocobro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usa_limites_default',
            field=models.BooleanField(default=True, help_text='Usar límites definidos generales definidos por el administrador'),
        ),
        migrations.CreateModel(
            name='LimiteTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_limite_diario', models.DecimalField(decimal_places=8, default=Decimal('100000000.00'), help_text='El monto máximo total con el que pueden operar los clientes en un día', max_digits=20)),
                ('monto_limite_mensual', models.DecimalField(decimal_places=8, default=Decimal('800000000.00'), help_text='El monto máximo total con el que pueden operar los clientes en el mes', max_digits=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('moneda_limites', models.ForeignKey(help_text='Moneda en la que está expresada los límites', on_delete=django.db.models.deletion.PROTECT, to='divisas.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='LimiteTransaccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_limite_diario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Límite máximo diario de transacciones (0 = sin límite)', max_digits=15)),
                ('monto_limite_mensual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Límite máximo mensual de transacciones (0 = sin límite)', max_digits=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites', to='clientes.cliente')),
                ('moneda_limite', models.ForeignKey(help_text='Moneda en la que están expresados los límites', on_delete=django.db.models.deletion.PROTECT, to='divisas.moneda')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limites_transaccion_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
