# Generated by Django 5.2.4 on 2025-09-25 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_usa_limites_default_limitetransaccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitetransaccioncliente',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limites', to='clientes.cliente'),
        ),
    ]
