# Generated by Django 5.2.4 on 2025-09-25 21:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_limitetransaccioncliente_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitetransaccioncliente',
            name='monto_limite_diario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Límite diario en PYG aplicado al total acumulado del monto de transacciones.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='limitetransaccioncliente',
            name='monto_limite_mensual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Límite mensual en PYG aplicado al total acumulado del monto de transacciones.', max_digits=15),
        ),
        migrations.DeleteModel(
            name='LimiteTransaccion',
        ),
    ]
