# Generated by Django 5.2.4 on 2025-08-26 07:17

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_metodo', models.CharField(choices=[('BANK_TRANSFER', 'Transferencia Bancaria'), ('DIGITAL_WALLET', 'Billetera Digital'), ('CREDIT_CARD', 'Tarjeta de Crédito'), ('DEBIT_CARD', 'Tarjeta de Débito'), ('CASH', 'Efectivo'), ('CHECK', 'Cheque')], max_length=20)),
                ('grupo_metodo', models.CharField(choices=[('BANKING', 'Banca y Transferencias'), ('CARDS', 'Tarjetas de Crédito/Débito'), ('DIGITAL_WALLETS', 'Billeteras Digitales Locales'), ('INTERNATIONAL_WALLETS', 'Billeteras Internacionales'), ('CASH_PICKUP', 'Retiro en Caja')], default='BANKING', help_text='Grupo al que pertenece este método de pago', max_length=30)),
                ('esta_activo', models.BooleanField(default=True)),
                ('soporta_compra', models.BooleanField(default=True)),
                ('soporta_venta', models.BooleanField(default=True)),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tiempo_procesamiento_horas', models.PositiveIntegerField(default=24, help_text='Tiempo de procesamiento en horas')),
                ('porcentaje_comision', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Comisión como porcentaje', max_digits=5)),
                ('comision_fija', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Comisión fija', max_digits=10)),
                ('instrucciones', models.TextField(blank=True, help_text='Instrucciones para el usuario')),
                ('configuracion', models.JSONField(default=dict, help_text='Configuración específica del método de pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'divisas_metodo_pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de la moneda (USD, EUR, PYG, etc.)', max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('simbolo', models.CharField(max_length=10)),
                ('esta_activa', models.BooleanField(default=True)),
                ('es_moneda_base', models.BooleanField(default=False, help_text='Moneda base para cálculos (solo una puede ser base)')),
                ('comision_compra', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Comisión aplicada en la compra de la moneda', max_digits=20)),
                ('comision_venta', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Comisión aplicada en la venta de la moneda', max_digits=20)),
                ('lugares_decimales', models.PositiveIntegerField(default=2)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='iconos_moneda/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'db_table': 'divisas_moneda',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='AlertaTasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('RATE_INCREASE', 'Subida de Tasa'), ('RATE_DECREASE', 'Bajada de Tasa'), ('RATE_TARGET', 'Tasa Objetivo'), ('VOLATILITY', 'Alta Volatilidad')], max_length=20)),
                ('tasa_objetivo', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('cambio_porcentual', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de cambio para activar alerta', max_digits=5, null=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('ultima_activacion', models.DateTimeField(blank=True, null=True)),
                ('conteo_activaciones', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_tasa', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='divisas.moneda')),
            ],
            options={
                'verbose_name': 'Alerta de Tasa',
                'verbose_name_plural': 'Alertas de Tasa',
                'db_table': 'divisas_alerta_tasa',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PrecioBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=8, help_text='Precio base de la moneda en la moneda base', max_digits=20)),
                ('esta_activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasas_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precio_base', to='divisas.moneda')),
                ('moneda_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precio_base_base', to='divisas.moneda')),
            ],
            options={
                'verbose_name': 'Precio Base',
                'verbose_name_plural': 'Precios Base',
                'db_table': 'divisas_precios_base',
                'ordering': ['-fecha_actualizacion'],
                'unique_together': {('moneda', 'moneda_base', 'esta_activa')},
            },
        ),
        migrations.CreateModel(
            name='HistorialTasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_compra', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Tasa de compra en la fecha de la marca de tiempo', max_digits=20)),
                ('tasa_venta', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Tasa de venta en la fecha de la marca de tiempo', max_digits=20)),
                ('comision_compra', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Comisión de compra en la fecha de la marca de tiempo', max_digits=20)),
                ('comision_venta', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Comisión de venta en la fecha de la marca de tiempo', max_digits=20)),
                ('marca_de_tiempo', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_tasa_cambio', to='clientes.categoriacliente')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_tasa_cambio', to='divisas.moneda')),
                ('moneda_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_tasa_cambio_base', to='divisas.moneda')),
                ('precio_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_tasa_cambio_precio_base', to='divisas.preciobase')),
            ],
            options={
                'verbose_name': 'Historial de Tasa de Cambio',
                'verbose_name_plural': 'Historial de Tasas de Cambio',
                'db_table': 'divisas_historial_tasas_cambio',
                'ordering': ['-marca_de_tiempo'],
                'indexes': [models.Index(fields=['moneda', 'marca_de_tiempo'], name='divisas_his_moneda__d46411_idx'), models.Index(fields=['marca_de_tiempo'], name='divisas_his_marca_d_e317f0_idx'), models.Index(fields=['categoria_cliente', 'marca_de_tiempo'], name='divisas_his_categor_ad14be_idx')],
            },
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('tasa_compra', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Tasa de compra', max_digits=20)),
                ('tasa_venta', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Tasa de venta', max_digits=20)),
                ('categoria_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas_cambio_categoria', to='clientes.categoriacliente')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas_cambio', to='divisas.moneda')),
                ('moneda_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas_cambio_base', to='divisas.moneda')),
                ('precio_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas_cambio_relacionadas', to='divisas.preciobase')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'db_table': 'divisas_tasas_cambio',
                'unique_together': {('moneda', 'moneda_base', 'categoria_cliente', 'esta_activa')},
            },
        ),
    ]
