# Generated by Django 5.2.4 on 2025-08-26 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasacambio',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas_cambio', to='divisas.moneda'),
        ),
    ]
