# Generated by Django 5.2.4 on 2025-08-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtasacambio',
            name='precio_base',
            field=models.DecimalField(decimal_places=8, help_text='Precio base de la moneda en la moneda base en el momento histórico', max_digits=20),
        ),
    ]
