# Generated by Django 5.2.4 on 2025-08-27 11:07

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0002_alter_historialtasacambio_precio_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='pais',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
