# Generated by Django 5.2.4 on 2025-08-27 22:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0003_moneda_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciobase',
            name='precio_base',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Precio base de la moneda en la moneda base', max_digits=20),
        ),
    ]
