# Generated by Django 5.2.4 on 2025-08-29 01:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0004_alter_preciobase_precio_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='denominacion_minima',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.01'), help_text='Denominación mínima para operaciones con esta moneda', max_digits=20),
        ),
        migrations.AddField(
            model_name='moneda',
            name='disponible_para_compra',
            field=models.BooleanField(default=True, help_text='Si está disponible para operaciones de compra'),
        ),
        migrations.AddField(
            model_name='moneda',
            name='disponible_para_venta',
            field=models.BooleanField(default=True, help_text='Si está disponible para operaciones de venta'),
        ),
        migrations.AddField(
            model_name='moneda',
            name='precio_base_inicial',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Precio base inicial al crear la moneda', max_digits=20),
        ),
        migrations.AddField(
            model_name='moneda',
            name='stock_inicial',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Stock inicial disponible de la moneda', max_digits=20),
        ),
    ]
