# Generated by Django 5.2.4 on 2025-09-04 21:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0005_agregar_campos_crud_monedas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='denominacion_minima',
            field=models.DecimalField(decimal_places=0, default=Decimal('1'), help_text='Denominación mínima para operaciones con esta moneda', max_digits=20),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='stock_inicial',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Stock inicial disponible de la moneda', max_digits=20),
        ),
    ]
