# Generated by Django 5.2.4 on 2025-09-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0006_eliminar_decimales_denominacion_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_metodo', models.CharField(choices=[('BANK_TRANSFER', 'Transferencia Bancaria'), ('DIGITAL_WALLET', 'Billetera Digital'), ('CASH', 'Efectivo'), ('CHECK', 'Cheque')], max_length=20)),
                ('grupo_metodo', models.CharField(choices=[('BANKING', 'Banca y Transferencias'), ('DIGITAL_WALLETS', 'Billeteras Digitales'), ('CASH_PICKUP', 'Retiro en Caja')], default='BANKING', help_text='Grupo al que pertenece este método de cobro', max_length=30)),
                ('esta_activo', models.BooleanField(default=True)),
                ('soporta_compra', models.BooleanField(default=True)),
                ('soporta_venta', models.BooleanField(default=True)),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Método de Cobro',
                'verbose_name_plural': 'Métodos de Cobro',
                'db_table': 'divisas_metodo_cobro',
                'ordering': ['nombre'],
            },
        ),
    ]
