# Generated by Django 5.2.4 on 2025-09-25 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0007_metodocobro'),
    ]

    operations = [
    ]
