# Generated by Django 5.2.4 on 2025-09-25 23:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0008_metodocobro_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodocobro',
            name='comision_fija',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Comisión fija', max_digits=10),
        ),
        migrations.AddField(
            model_name='metodocobro',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Comisión como porcentaje', max_digits=5),
        ),
    ]
