# Generated by Django 5.2.4 on 2025-09-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0009_metodocobro_comision_fija_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodocobro',
            name='porcentaje_visual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión visual (0-100)', max_digits=6),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='porcentaje_visual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión visual (0-100)', max_digits=6),
        ),
    ]
