# Generated by Django 5.2.4 on 2025-09-26 01:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0010_metodocobro_porcentaje_visual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodocobro',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.0000'), help_text='Comisión como porcentaje', max_digits=2),
        ),
        migrations.AlterField(
            model_name='metodocobro',
            name='porcentaje_visual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='porcentaje_visual',
            field=models.IntegerField(default=0),
        ),
    ]
