# Generated by Django 5.2.4 on 2025-09-26 01:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0011_alter_metodocobro_porcentaje_comision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodocobro',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Comisión como porcentaje', max_digits=5),
        ),
    ]
